### ISSUE TITLE
Can't get a fine tune run going.

### ISSUE THREAD

**Issue by JeffryCA** [IIEleven11/StyleTTS2FineTune#13]
I am trying to fine tune on a custom voice in german. I followed the steps (to the best of my knowledge) but when I run the command 

```bash
accelerate launch --mixed_precision=fp16 --num_processes=2 train_finetune_accelerate.py --config_path ./Configs/config_ft.yml
```

I get the following error (see bottom). Can you help me or point out what I am doing wrong?

Steps:
1. Generate and replace wavs folder and train and validate txt file. 
2. Download models and put them in their respective dict (replaced the with multilingual BERT)

I am trying to train on a Vertex AI jupyter notebook + 2 (T4) GPUs setup. (In case that matters).

Used the following config (tried to match yours 1:1 just to get a test run going):

```yaml

log_dir: "Models/LJSpeech"
save_freq: 5
log_interval: 10
device: "cuda"
epochs: 350 # number of finetuning epoch (1 hour of data)
batch_size: 2
max_len: 500 # maximum number of frames
pretrained_model: "Models/LibriTTS/epochs_2nd_00020.pth"
second_stage_load_pretrained: true # set to true if the pre-trained model is for 2nd stage
load_only_params: true # set to true if do not want to load epoch numbers and optimizer parameters

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00080.pth"
PLBERT_dir: 'Utils/PLBERT/'

data_params:
  train_data: "Data/train_list.txt"
  val_data: "Data/val_list.txt"
  root_path: "Data/wavs"
  OOD_data: "Data/OOD_texts.txt"
  min_length: 50 # sample until texts with this size are obtained for OOD texts

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  multispeaker: true

  dim_in: 64 
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80

  n_token: 178 # number of phoneme tokens
  max_dur: 50 # maximum duration of a single phoneme
  style_dim: 128 # style vector size
  
  dropout: 0.2

  # config for decoder
  decoder: 
      type: 'hifigan' # either hifigan or istftnet
      resblock_kernel_sizes: [3,7,11]
      upsample_rates :  [10,5,3,2]
      upsample_initial_channel: 512
      resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
      upsample_kernel_sizes: [20,10,6,4]
      
  # speech language model config
  slm:
      model: 'microsoft/wavlm-base-plus'
      sr: 16000 # sampling rate of SLM
      hidden: 768 # hidden size of SLM
      nlayers: 13 # number of layers of SLM
      initial_channel: 64 # initial channels of SLM discriminator head
  
  # style diffusion model config
  diffusion:
    embedding_mask_proba: 0.1
    # transformer config
    transformer:
      num_layers: 3
      num_heads: 8
      head_features: 64
      multiplier: 2

    # diffusion distribution config
    dist:
      sigma_data: 0.2 # placeholder for estimate_sigma_data set to false
      estimate_sigma_data: true # estimate sigma_data from the current batch if set to true
      mean: -3.0
      std: 1.0
  
loss_params:
    lambda_mel: 2. # mel reconstruction loss
    lambda_gen: 1. # generator loss
    lambda_slm: 1. # slm feature matching loss
    
    lambda_mono: 1. # monotonic alignment loss (TMA)
    lambda_s2s: 1. # sequence-to-sequence loss (TMA)

    lambda_F0: 3. # F0 reconstruction loss
    lambda_norm: 1. # norm reconstruction loss
    lambda_dur: 1. # duration loss
    lambda_ce: 20. # duration predictor probability output CE loss
    lambda_sty: 1. # style reconstruction loss
    lambda_diff: 1. # score matching loss
    
    diff_epoch: 20 # style diffusion starting epoch
    joint_epoch: 30 # joint training starting epoch

optimizer_params:
  lr: 0.0001 # general learning rate
  bert_lr: 0.00001 # learning rate for PLBERT
  ft_lr: 0.0001 # learning rate for acoustic modules
  
slmadv_params:
  min_len: 300 # minimum length of samples
  max_len: 400 # maximum length of samples
  batch_percentage: 0.5 # to prevent out of memory, only use half of the original batch size
  iter: 10 # update the discriminator every this iterations of generator update
  thresh: 5 # gradient norm above which the gradient is scaled
  scale: 0.01 # gradient scaling factor for predictors from SLM discriminators
  sig: 1.5 # sigma for differentiable duration modeling
  
```

Error:

```bash
The following values were not passed to `accelerate launch` and had defaults used instead:
                More than one GPU was found, enabling multi-GPU training.
                If this was unintended please pass in `--num_processes=1`.
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
bert loaded
bert loaded
bert_encoder loaded
bert_encoder loaded
predictor loaded
predictor loaded
decoder loaded
decoder loaded
text_encoder loaded
text_encoder loaded
predictor_encoder loaded
predictor_encoder loaded
style_encoder loaded
style_encoder loaded
diffusion loaded
diffusion loaded
text_aligner loaded
text_aligner loaded
pitch_extractor loaded
pitch_extractor loaded
mpd loaded
mpd loaded
msd loaded
msd loaded
wd loaded
wd loaded
BERT AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.9, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 1e-05
    lr: 1e-05
    max_lr: 2e-05
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.01
)
decoder AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.0, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 0.0001
    lr: 0.0001
    max_lr: 0.0002
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.0001
)
BERT AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.9, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 1e-05
    lr: 1e-05
    max_lr: 2e-05
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.01
)
decoder AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.0, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 0.0001
    lr: 0.0001
    max_lr: 0.0002
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.0001
)
...
wavefile.wav (shortened but file names are listed here)
...
am anfaŋ ɡɑːp ɛs ɪmɜ nɔx zoː atɾiːbuːtə oːdɜ nyːɑ̃sən voː man zɑːkt oːkɛɪ vɑːrʊm maxt das diː rɔlə  (Why do these appear?)
...
wavefile.wav .wav (shortened but file names are listed here)
...
Traceback (most recent call last):
  File "/home/jupyter/StyleTTS2FineTune/StyleTTS2/train_finetune_accelerate.py", line 714, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jupyter/StyleTTS2FineTune/StyleTTS2/train_finetune_accelerate.py", line 403, in main
    y_rec_gt_pred = model.decoder(en, F0_real, N_real, s)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/StyleTTS2FineTune/StyleTTS2/Modules/hifigan.py", line 457, in forward
    F0 = self.F0_conv(F0_curve.unsqueeze(1))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [1, 1, 3], expected input[1, 500, 1] to have 1 channels, but got 500 channels instead

...
wavefile.wav (shortened but file names are listed here)
...
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
...
wavefile.wav (shortened but file names are listed here)
...
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
...
wavefile.wav (shortened but file names are listed here)
...
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
...
wavefile.wav (shortened but file names are listed here)
...
daɡeːɡən vɪɾt diː ɛɾklɛːrʊŋ pɛɾ eː(en)meɪl(de) eːɜ viː aɪn tsuːɡaŋ ʊntɜ apveːzəndən bəhandəlt alzoː danax ɡəfrɑːkt van mɪt dɛɾ kɛntnɪsnɑːmə tyːpɪʃɜvaɪzə tsuː rɛçnən ɪst 
daɡeːɡən vɪɾt diː ɛɾklɛːrʊŋ pɛɾ eː(en)meɪl(de) eːɜ viː aɪn tsuːɡaŋ ʊntɜ apveːzəndən bəhandəlt alzoː danax ɡəfrɑːkt van mɪt dɛɾ kɛntnɪsnɑːmə tyːpɪʃɜvaɪzə tsuː rɛçnən ɪst 
daɡeːɡən vɪɾt diː ɛɾklɛːrʊŋ pɛɾ eː(en)meɪl(de) eːɜ viː aɪn tsuːɡaŋ ʊntɜ apveːzəndən bəhandəlt alzoː danax ɡəfrɑːkt van mɪt dɛɾ kɛntnɪsnɑːmə tyːpɪʃɜvaɪzə tsuː rɛçnən ɪst 
daɡeːɡən vɪɾt diː ɛɾklɛːrʊŋ pɛɾ eː(en)meɪl(de) eːɜ viː aɪn tsuːɡaŋ ʊntɜ apveːzəndən bəhandəlt alzoː danax ɡəfrɑːkt van mɪt dɛɾ kɛntnɪsnɑːmə tyːpɪʃɜvaɪzə tsuː rɛçnən ɪst 
...
wavefile.wav (shortened but file names are listed here)
...
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
ɛntʃaɪdənt dyɾftə fiːlmeːɾ dɛɾ diːaloːɡɪʃə karaktɜ dɛs (en)tʃats(de) oːdɜ ɛːnlɪçəs zaɪn 
...
wavefile.wav (shortened but file names are listed here)
...
dɔnɜstaɡnaxt ʃraɪpt ɛɾ deːm ɑː aɪnə eː(en)meɪl(de) voːnax ɛɾ das anɡəboːt aneːmə 
dɔnɜstaɡnaxt ʃraɪpt ɛɾ deːm ɑː aɪnə eː(en)meɪl(de) voːnax ɛɾ das anɡəboːt aneːmə 
dɔnɜstaɡnaxt ʃraɪpt ɛɾ deːm ɑː aɪnə eː(en)meɪl(de) voːnax ɛɾ das anɡəboːt aneːmə 
dɔnɜstaɡnaxt ʃraɪpt ɛɾ deːm ɑː aɪnə eː(en)meɪl(de) voːnax ɛɾ das anɡəboːt aneːmə 
...
wavefile.wav (shortened but file names are listed here)
...
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
ɑː hatə tatzɛçlɪç ɪn zaɪnɜ (en)meɪlbɒks(de) nɔx ɡɑːɾnɪçt naxɡeːzeːən dɑː ɛɾ diː lɛtstən tɑːɡə zeːɾ bəʃɛftɪçt vɑːɾ 
...
wavefile.wav (shortened but file names are listed here)
...
Epochs: 1
Traceback (most recent call last):
  File "/home/jupyter/StyleTTS2FineTune/StyleTTS2/train_finetune_accelerate.py", line 714, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jupyter/StyleTTS2FineTune/StyleTTS2/train_finetune_accelerate.py", line 684, in main
    logger.info('Validation loss: %.3f, Dur loss: %.3f, F0 loss: %.3f' % (loss_test / iters_test, loss_align / iters_test, loss_f / iters_test) + '\n\n\n')
ZeroDivisionError: division by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3735) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1073, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 718, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_finetune_accelerate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-03_12:07:06
  host      : xxx
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3736)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-03_12:07:06
  host      : xxx
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3735)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
